### ISSUE TITLE
VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by megacorvega** [TheFireKahuna/equalizerAPO64#1]
After replacing the APO installation with the zipped files, I'm getting a VCRUNTIME140_1.dll not found when trying to run the configurator. Couldn't find the file in the backup folder I made either.

**Comment by megacorvega** [comment]
FIxed it. Must install Microsoft VIsual C++ Redis 2015-2019.

**Comment by TheFireKahuna** [comment]
Good catch, added a line about the Redistributable to the install instructions. Ty
